language: java
jdk:
    -openjdk8
addons:
    sonarcloud:
        organization:"unimibsoftengcourse1920"
        token:
            secure: $SONAR_TOKEN 59ed3de7cef069709f73a5f673bbb16547ab6397
script:
    -mvn sonar:sonar
